### ISSUE TITLE
Do you plan making RSDKv5U Port for the wii u?

### ISSUE THREAD

**Issue by popeye820** [Clownacy/Sonic-Mania-Decompilation-Wii-U#6]
Would be cool if u made a port of rsdkv5u for the wii u becouse u arleady ported rsdkv5 it shouldnt be hard to port rsdkv5u

**Comment by Clownacy** [comment]
I already ported RSDKv5U to the Wii U: every release of my Mania port used it until v1.0.2, when I switched to RSDKv5 to fix an issue with Heavy Shinobi. [v1.0.1](https://github.com/Clownacy/Sonic-Mania-Decompilation-Wii-U/releases/tag/v1.0.1) was the last release to use RSDKv5U.

**Comment by popeye820** [comment]
Question Can i use the origins rsdk on the v1.0.1 releases then?

**Comment by Clownacy** [comment]
I think so, but I can't check since I don't have Origins. Sonic 1, 2, and CD should work, but Sonic 3 won't.

I've heard that there won't be any sounds or music, since the RSDK files are missing them, so you'd have to extract the RSDK files and then add the sounds and music files from the mobile versions to them.

**Comment by popeye820** [comment]
Yeah, iknow about the sound  Is there away to change where rsdk file is located? i want to have sonic mania and the other games in the same time.

**Comment by Clownacy** [comment]
There's an option in the settings.ini file that specifies the name of the RSDK file: `dataFile`.
